
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='emojifs',
    version='0.1.0',
    description='A FUSE filesystem to manipulate custom emojis on your various Slacks and Discords',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/cdanis/emojifs", "repository": "https://github.com/cdanis/emojifs"},
    author='Chris Danis',
    author_email='cdanis@gmail.com',
    license='GPL-3.0-only',
    keywords='fuse slack discord emoji',
    classifiers=['Development Status :: 3 - Alpha', 'Environment :: No Input/Output (Daemon)', 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)', 'Topic :: Communications', 'Topic :: System :: Filesystems'],
    entry_points={"console_scripts": ["emojifs = emojifs.__main__:main"]},
    packages=['emojifs'],
    package_dir={"": "."},
    package_data={},
    install_requires=['cachetools==4.*,>=4.0.0', 'logzero==1.*,>=1.5.0', 'refuse==0.*,>=0.0.0', 'requests==2.*,>=2.0.0', 'tomlkit==0.*,>=0.6.0'],
    extras_require={"dev": ["bpython", "dephell==0.*,>=0.8.3", "flake8", "pytest==4.*,>=4.6.0"]},
)
